services:
    _defaults:
        autowire: true
        autoconfigure: true

    OHMedia\VideoBundle\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/OHMediaVideoBundle.php'
